name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  CSV_URL: "MLproject/processed_data.csv"
  TARGET_VAR: "Heart_Attack_Prediction"


jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
          
      # Install Conda and create environment from conda.yaml
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: heart-attack-predictor
          auto-activate-base: false
          
       # Initialize Conda for bash shell
      - name: Initialize Conda
        run: |
          echo "Initializing Conda for bash"
          conda init bash
          source ~/.bashrc  # Apply the changes made by 'conda init'

      # Install MLflow and dependencies
      - name: Install MLflow and dependencies
        run: |
          source ~/.bashrc  # Ensure shell configuration is reloaded
          conda activate heart-attack-predictor  # Ensure environment is activated
          pip install mlflow  # Install mlflow if it wasn't installed in the environment
          pip install -r MLProject/requirements.txt  # Optional, if there is a requirements.txt

      # Run MLflow Project
      - name: Run MLflow Project
        run: |
          source ~/.bashrc  # Ensure shell configuration is reloaded
          conda activate heart-attack-predictor  # Ensure environment is activated
          cd MLProject
          mlflow run . -P data_path=processed_data.csv --env-manager=local

      # Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          source ~/.bashrc
          conda activate heart-attack-predictor
          # Cek jika direktori mlruns/0 ada dan menampilkan kontennya
          echo "Checking contents of MLProject/mlruns/0/"
          ls -l MLProject/mlruns/0/
          RUN_ID=$(ls -td MLProject/mlruns/0/*/ | head -n 1 | cut -d'/' -f4)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
      # Verify the existence of the model directory for RUN_ID
      - name: Verify model directory exists for RUN_ID
        run: |
          source ~/.bashrc
          conda activate heart-attack-predictor
          echo "Verifying the model directory for RUN_ID: $RUN_ID"
          if [ ! -d "MLProject/mlruns/0/$RUN_ID/artifacts/model" ]; then
            echo "Model not found for RUN_ID: $RUN_ID. Exiting."
            exit 1
          fi
      # ✅ Tambahkan langkah ini untuk menyimpan mlruns/ ke GitHub
      - name: Push changes to repository
        run: |
          git config --global user.name "M Mahfudl Awaludin"
          git config --global user.email "mahfudlawaludin.26@gmail.com"
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GH_PAT }}@github.com/M-Mahfudl-Awaludin/Workflow-CI.git
          git add .
          git commit -m "Save mlruns from CI run" || echo "No changes to commit"
          git push origin main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
            
