name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  CSV_URL: "MLproject/processed_data.csv"
  TARGET_VAR: "Heart_Attack_Prediction"


jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
          
      # Install Conda and create environment from conda.yaml
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: heart-attack-predictor
          auto-activate-base: false
          
      # Initialize Conda to allow 'conda activate'
      - name: Initialize Conda
        run: |
          conda init bash  # Initialize conda for bash shell
          source ~/.bashrc  # Apply the changes made by 'conda init'
      
      # Install MLflow and dependencies
      - name: Install MLflow and dependencies
        run: |
          conda activate heart-attack-predictor
          pip install mlflow  # Install mlflow if it wasn't installed in the environment
          pip install -r MLProject/requirements.txt  # Optional, jika ada file requirements.txt

      # Run MLflow Project
      - name: Run MLflow Project
        run: |
          conda activate heart-attack-predictor  # Ensure conda environment is activated
          cd MLProject
          mlflow run . -P data_path=processed_data.csv --env-manager=local

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . -P data_path=processed_data.csv --env-manager=local 
          
      # Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "workflow-c"
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.mahfudl26 }}
          password: ${{ secrets.dckr_pat_3Sv0IUByX9n_lIerWEIIlr-uRYo }}

      - name: Tag Docker image
        run: |
          docker tag heartattack-model ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci:latest
