name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: heart_attack_env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow
        run: |
          pip install mlflow

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . -P data_path=processed_data.csv --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          cd MLProject
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f2)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Build Docker Model
        run: |
          cd MLProject
          mlflow models build-docker --model-uri "file://$(pwd)/mlruns/0/$RUN_ID/artifacts/model" --name "heartattack-model"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.mahfudl26 }}
          password: ${{ secrets.dckr_pat_3Sv0IUByX9n_lIerWEIIlr-uRYo }}

      - name: Tag Docker image
        run: |
          docker tag heartattack-model ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci:latest
